services:
  # Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: unicampo_db
      DB_USERNAME: unicampo_user
      DB_PASSWORD: unicampo_password


  #Vue.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules 
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true  
      - WDS_SOCKET_HOST=0.0.0.0  
      - FAST_REFRESH=false 

  #MySQL
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: unicampo_db
      MYSQL_USER: unicampo_user
      MYSQL_PASSWORD: unicampo_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"

volumes:
  db_data: