services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    volumes:
      - ./backend:/var/www/html:cached
      - /var/www/html/vendor
      - /var/www/html/node_modules
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: unicampo_db
      DB_USERNAME: unicampo_user
      DB_PASSWORD: unicampo_password
      PHP_OPCACHE_ENABLE: 1
      PHP_OPCACHE_MEMORY_CONSUMPTION: 256
      PHP_OPCACHE_MAX_ACCELERATED_FILES: 20000
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 0
      PHP_OPCACHE_REVALIDATE_FREQ: 0

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WDS_SOCKET_HOST: "0.0.0.0"
      FAST_REFRESH: "false"
      NODE_OPTIONS: "--max-old-space-size=4096"

  # MySQL 8
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: unicampo_db
      MYSQL_USER: unicampo_user
      MYSQL_PASSWORD: unicampo_password
    ports:
      - "3306:3306"
    command: >
      --innodb-buffer-pool-size=512M
      --innodb-log-file-size=128M
      --max-connections=200
      --table-open-cache=4000
      --thread-cache-size=100
      --open-files-limit=65535
      --innodb-flush-method=O_DIRECT
      --innodb-flush-log-at-trx-commit=2
      --innodb-file-per-table=1
      --innodb-io-capacity=2000
      --innodb-io-capacity-max=4000
      --innodb-read-io-threads=4
      --innodb-write-io-threads=4
      --tmp-table-size=64M
      --max-heap-table-size=64M
      --slow-query-log=1
      --long-query-time=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data: