services:
  # Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: unicampo_db
      DB_USERNAME: unicampo_user
      DB_PASSWORD: unicampo_password


  #Vue.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules 
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true  
      - WDS_SOCKET_HOST=0.0.0.0  
      - FAST_REFRESH=false 

  #MySQL
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: unicampo_db
      MYSQL_USER: unicampo_user
      MYSQL_PASSWORD: unicampo_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    command: >
      --innodb-buffer-pool-size=256M
      --innodb-log-file-size=64M
      --max-connections=100
      --table-open-cache=2000
      --query-cache-type=1
      --query-cache-size=32M
      --thread-cache-size=50
      --open-files-limit=65535
      --innodb-flush-method=O_DIRECT
      --innodb-flush-log-at-trx-commit=2

volumes:
  db_data: